<?php

namespace Proxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PersonalAccessToken extends \App\Entities\PersonalAccessToken implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abilities' => [parent::class, 'abilities', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'expires_at' => [parent::class, 'expires_at', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'last_used_at' => [parent::class, 'last_used_at', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'token' => [parent::class, 'token', null, 16],
        "\0".parent::class."\0".'tokenable' => [parent::class, 'tokenable', null, 16],
        "\0".parent::class."\0".'tokenable_id' => [parent::class, 'tokenable_id', null, 16],
        "\0".parent::class."\0".'tokenable_type' => [parent::class, 'tokenable_type', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'abilities' => [parent::class, 'abilities', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'expires_at' => [parent::class, 'expires_at', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'last_used_at' => [parent::class, 'last_used_at', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'token' => [parent::class, 'token', null, 16],
        'tokenable' => [parent::class, 'tokenable', null, 16],
        'tokenable_id' => [parent::class, 'tokenable_id', null, 16],
        'tokenable_type' => [parent::class, 'tokenable_type', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
